### ISSUE TITLE
images

### ISSUE THREAD

**Issue by librarianofbabel** [overactor/LobThis#2]
![icon32](https://cloud.githubusercontent.com/assets/12650463/7876288/70685666-0597-11e5-9eeb-d6008cf21dc6.png)

**Comment by librarianofbabel** [comment]
![icon48](https://cloud.githubusercontent.com/assets/12650463/7876289/7365c772-0597-11e5-9e68-aa53482685bd.png)

**Comment by librarianofbabel** [comment]
![icon128](https://cloud.githubusercontent.com/assets/12650463/7876290/75ad55d6-0597-11e5-931f-5457c0b605b9.png)

**Comment by rik-degraaff** [comment]
@librarianofbabel  I've added the icons in the newest commit.
