### ISSUE TITLE
pem file

### ISSUE THREAD

**Issue by librarianofbabel** [overactor/LobThis#3]
Hey overactor,

I'm going to try to publish the extension now. My only concern is having the .pem file in the GitHub project - I believe if that is public, someone could use that to create a malicious program and pass it off as an update of our extension. Then anyone using our extension might download it unsuspectingly. I think it's best if you just keep a version on your hard drive, or whatever you use for storage.

**Comment by rik-degraaff** [comment]
Wow @librarianofbabel ,  I hadn't noticed I put that up.
Is there any way you could switch the pem file you're using for the released version?
I've deleted the pem file, but we should not take risks there.

**Comment by librarianofbabel** [comment]
No worries! It turns out that the chrome store doesn't use them - they're only for extensions that are being distributed independently. Updates through the Chrome store are just done through a Chrome developer account. So there's no need to worry. 

Perhaps we should just change the PEM file for the version on github - some people may still want to install it themselves.

Thanks again for creating this project! I'm very pleased with how it's developed.

**Comment by rik-degraaff** [comment]
As far as I know people can easily have their own pem file generated while packaging the extension. I'll go ahead and close this issue.
